flags:
  kestrel:
    library-only: false
    dev: false
packages:
- '.'
- location:
    git: git@github.com:cutsea110/owl-auth
    commit: FIX-2015
extra-deps:
- utility-ht-0.0.11
- yesod-pnotify-0.6.0
- thumbnail-0.8.0
resolver: lts-3.10
