# Kestrel.hs
InvalidAccount: Your account is invalid.
TOC: Table of Contents

# Profile.hs
CouldntAccessAnotherUserProfile: you couldn't access another user profile.
UpdatedProfile: your profile updated.

# Wiki.hs
ConflictOccurred: Conflict occurred. Your changes couldn't be propagated.
ChangesSince time@UTCTime: Changes since #{showDate time}.
ChangesBetween from@UTCTime to@UTCTime: Changes between #{showDate from} and #{showDate to}

# default-layout
Tools: Tools
Go: Go
SearchPlaceholder: Search...
UploadFile: Upload file
Login: Login

# default-layout.julius
RecentChanges: Recent Changes
Gallery: Gallery
Editing page@Text: #{page} Editing.
WarnFieldsRequired: Fields are required.

# wiki.julius
ShowTOC: show TOC
HideTOC: hide TOC
NullText: *** no comment log ***

# header
NowLogin: You are now logged in.
Logout: Logout
ChangePassword: Set password.
FileGallery: Upload File
ChangeProf: change your nickname.
SimpleFileUploader: simple file uploader

# login
AccountID: Account ID
Password: Password
LoginViaAccount: Login via account
LoginViaOpenID: Login via OpenID

# profile
ProfileSettings: Profile Settings
NickName: Nickname

# wiki
VIEW: View
EDIT: Edit
DELETE: Delete
HISTORY: History
TOP: Top
LastEditor: Editor
LastUpdatedDate: Updated Date
Preview: preview
MorePreview: more preview
Update: update
CreateNew: create new
REVERT: Revert
