# default-layout
Tools: 検索ツール
Go: Go
SearchPlaceholder: Search...
UploadFile: ファイルをアップロードする
Login: ログイン

# default-layout.julius
RecentChanges: 最近の更新
Gallery: ファイルギャラリー
Editing page@Text: #{page}を編集する
WarnFieldsRequired: 必須入力項目です.

# wiki.julius
ShowTOC: 目次を表示する
HideTOC: 目次を非表示にする
NullText: *** 変更メモなし ***

# header
NowLogin: ログイン中
Logout: ログアウト
ChangePassword: パスワード変更
FileGallery: アップロードファイル
ChangeProf: プロフィール変更はこちらから
SimpleFileUploader: 簡易ファイルアップローダ

# login
AccountID: アカウントID
Password: パスワード
LoginViaAccount: このアカウントでログインする
LoginViaOpenID: OpenIDでログインする

# wiki
VIEW: 表示
EDIT: 編集
DELETE: 削除
HISTORY: 更新履歴
TOP: トップ
LastEditor: 最終更新者
LastUpdatedDate: 最終更新日時
