# Kestrel.hs
InvalidAccount: あなたのアカウントは無効です.
TOC: 目次

# Profile.hs
CouldntAccessAnotherUserProfile: 他人のプロフィールを見ることができません.
UpdatedProfile: プロフィールを更新しました.

# Wiki.hs
ConflictOccurred: 競合が発生しました.あなたの変更は反映できませんでした.
ChangesSince time@UTCTime: #{showDate time} 以降の変更
ChangesBetween from@UTCTime to@UTCTime: #{showDate from} から #{showDate to} の変更

# default-layout
Tools: 検索ツール
Go: Go
SearchPlaceholder: Search...
UploadFile: ファイルをアップロードする
Login: ログイン

# default-layout.julius
RecentChanges: 最近の更新
Gallery: ファイルギャラリー
Editing page@Text: #{page}を編集する
WarnFieldsRequired: 必須入力項目です.

# wiki.julius
ShowTOC: 目次を表示する
HideTOC: 目次を非表示にする
NullText: *** 変更メモなし ***

# header
NowLogin: ログイン中
Logout: ログアウト
ChangePassword: パスワード変更
FileGallery: アップロードファイル
ChangeProf: プロフィール変更はこちらから
SimpleFileUploader: 簡易ファイルアップローダ

# login
AccountID: アカウントID
Password: パスワード
LoginViaAccount: このアカウントでログインする
LoginViaOpenID: OpenIDでログインする

# profile
ProfileSettings: プロフィール設定
NickName: ニックネーム

# wiki
VIEW: 表示
EDIT: 編集
DELETE: 削除
HISTORY: 更新履歴
TOP: トップ
LastEditor: 最終更新者
LastUpdatedDate: 最終更新日時
Preview: プレビューする
MorePreview: もう一度プレビューする
Update: 更新する
CreateNew: 新規作成する
REVERT: 巻き戻し

# deleteWiki
ConfirmRemove path@Text: `#{path}' の削除確認.
RemoveAnyway: それでも削除する
Warning: 警告!
WarnForDelete: このコンテンツを削除すると更新履歴も含めて完全に削除されて二度と元に戻すことは出来ません.
ConfirmDeleteLastChance: 本当に削除しますか?
