Default: &defaults
  user: cutsea110
  password: cutsea110
  host: localhost
  port: 5432
  database: kestrel
  poolsize: 10

Development:
  database: kestrel_devel
  <<: *defaults

Test:
  database: kestrel_test
  <<: *defaults

Staging:
  database: kestrel_staging
  poolsize: 100
  <<: *defaults

Production:
  user: soubun
  password: sougoubunnka
  database: kestrel
  poolsize: 100
  <<: *defaults
