Default: &defaults
  host: "*4" # any IPv4 host
  port: 8080
  approot: "http://localhost:8080"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.example.com"
  <<: *defaults
