Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  approot: "http://soubun2.basement.timedia.co.jp"
  <<: *defaults

Production:
  #approot: "http://soubun2.basement.timedia.co.jp"
  approot: "http://soubun.seitoku.ac.jp"
  <<: *defaults
