Default: &defaults
  host: "localhost"
  port: 3000

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://soubun.seitoku.ac.jp"
  <<: *defaults
